language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.5
  - 2.7.0
before_script:
  - git config --global user.email "continuous-integration@nestacms.com"
  - git config --global user.name "Nesta CI"
script: bundle exec rake test
env:
  - REPORTER=default
