language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
before_script:
  - git config --global user.email "continuous-integration@nestacms.com"
  - git config --global user.name "Nesta CI"
script: bundle exec rake test
env:
  - REPORTER=default
